Add github job summary for spelling and a mistake for it to catch

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -15,6 +15,8 @@
 # specific language governing permissions and limitations
 # under the License.
 
+# Static analysis of website files. These jobs only require pnpm's dev dependencies and do not build or run the website.
+
 name: static
 
 on:
@@ -48,3 +50,13 @@ jobs:
       working-directory: ${{ env.script_dir }}
       run: |
         ./spelling.sh
+        rc=$?
+        if [ "$rc" != 0 ]; then
+          echo '## Spell check failed.
+          Spelling can also be checked locally by running the script *.github/scripts/spelling.sh*. This requires you to have pnpm's dev dependencies installed on your machine for cspell to work (run `pnpm install --dev`).
+          ** If spell check fails for words that are correct but not recognized:**
+            - Option 1: If the word is relevant for the whole Ozone project, add it to the `words` list in *cspell.yaml* so that it is considered valid.
+            - Option 2: If the word is only relevant for one specific page, add an [inline directive](https://cspell.org/configuration/document-settings/) as a comment in the markdown frontmatter of that page only.
+          ' >> $GITHUB_STEP_SUMMARY
+        fi
+        exit "$rc"
